// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVf0siFNV9lguW4UZt-2T5ozwn22tjz6k',
    appId: '1:171780322016:web:7441ebe1425db987c35685',
    messagingSenderId: '171780322016',
    projectId: 'edubook-fbf51',
    authDomain: 'edubook-fbf51.firebaseapp.com',
    storageBucket: 'edubook-fbf51.firebasestorage.app',
    measurementId: 'G-8GGFDG9DM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ4jKejcMYQXWMXyclHZHngMNGvbLBGtQ',
    appId: '1:171780322016:android:0a53517908a408fcc35685',
    messagingSenderId: '171780322016',
    projectId: 'edubook-fbf51',
    storageBucket: 'edubook-fbf51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDONSBr72YjqG5R-gBZxZuWyJ2xZ21x16k',
    appId: '1:171780322016:ios:02fe168e4929735dc35685',
    messagingSenderId: '171780322016',
    projectId: 'edubook-fbf51',
    storageBucket: 'edubook-fbf51.firebasestorage.app',
    iosBundleId: 'com.example.edubook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDONSBr72YjqG5R-gBZxZuWyJ2xZ21x16k',
    appId: '1:171780322016:ios:02fe168e4929735dc35685',
    messagingSenderId: '171780322016',
    projectId: 'edubook-fbf51',
    storageBucket: 'edubook-fbf51.firebasestorage.app',
    iosBundleId: 'com.example.edubook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVf0siFNV9lguW4UZt-2T5ozwn22tjz6k',
    appId: '1:171780322016:web:696439faa4900f2cc35685',
    messagingSenderId: '171780322016',
    projectId: 'edubook-fbf51',
    authDomain: 'edubook-fbf51.firebaseapp.com',
    storageBucket: 'edubook-fbf51.firebasestorage.app',
    measurementId: 'G-C70S2JTZBF',
  );

}