// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIvTsGh7XNwtI62jLTMLYhFP3INUIDzQQ',
    appId: '1:973735279660:web:6469c2a427b78d26a16589',
    messagingSenderId: '973735279660',
    projectId: 'classroombooking-a7d5c',
    authDomain: 'classroombooking-a7d5c.firebaseapp.com',
    storageBucket: 'classroombooking-a7d5c.firebasestorage.app',
    measurementId: 'G-466B29747L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQc87ZPAagUJSOAMmqxiBLpbo7ZJ4C0JY',
    appId: '1:973735279660:android:7a6fc958d9acbb27a16589',
    messagingSenderId: '973735279660',
    projectId: 'classroombooking-a7d5c',
    storageBucket: 'classroombooking-a7d5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJAXoDMZgXUvEvSKcIRnK15W9j4-iBhIw',
    appId: '1:973735279660:ios:29136db72f61a698a16589',
    messagingSenderId: '973735279660',
    projectId: 'classroombooking-a7d5c',
    storageBucket: 'classroombooking-a7d5c.firebasestorage.app',
    iosBundleId: 'com.example.classroomBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJAXoDMZgXUvEvSKcIRnK15W9j4-iBhIw',
    appId: '1:973735279660:ios:29136db72f61a698a16589',
    messagingSenderId: '973735279660',
    projectId: 'classroombooking-a7d5c',
    storageBucket: 'classroombooking-a7d5c.firebasestorage.app',
    iosBundleId: 'com.example.classroomBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIvTsGh7XNwtI62jLTMLYhFP3INUIDzQQ',
    appId: '1:973735279660:web:8b3d08b2d1d32151a16589',
    messagingSenderId: '973735279660',
    projectId: 'classroombooking-a7d5c',
    authDomain: 'classroombooking-a7d5c.firebaseapp.com',
    storageBucket: 'classroombooking-a7d5c.firebasestorage.app',
    measurementId: 'G-SDJMX8HFEG',
  );
}
